### ISSUE TITLE
How to add file size, please help thanks

### ISSUE THREAD

**Issue by houzhanshan** [ajith-ab/react-native-receive-sharing-intent#10]

**Comment by ajith-ab** [comment]
@houzhanshan now this feature is not available. hopefully, I am trying to add file size on next release

Thanks
Ajith A B

**Comment by 488taimoor** [comment]
when you are going to add file size ?

**Comment by 488taimoor** [comment]
add it as soon as possible.

**Comment by houzhanshan** [comment]
You can use 'rn-fetch-blob' to get the file size

import RNFetchBlob from 'rn-fetch-blob'

RNFetchBlob.fs.stat(path)
.then((stats) => {
      console.log(stats)
}).catch((err) => {})

**Comment by ajith-ab** [comment]
You should be able to use react-native-fs and use stat. Or you can use Image.getSize() with the filepath to return width and height.
