### ISSUE TITLE
Error: file type is Invalid regardless of file type 

### ISSUE THREAD

**Issue by maitham** [ajith-ab/react-native-receive-sharing-intent#14]
I'm using RN 0.62.2 , regardless of the filetype I pass in whether a web url, text or file I keep getting   [Error: file type is Invalid] when redirected to the host.

**Comment by maitham** [comment]
There was a typo in my app group, which meant the userDefaults weren't accessible.

**Comment by duylinhdang1998** [comment]
Hello 
how do fix that ? thanks

**Comment by luigbren** [comment]
> Hello how do fix that ? thanks


hello, I spent many hours trying to make it work on iOS and nothing, until I got it to work, I read that it was a problem with the group.name, simply I opened the file "ShareViewController.swift", search and replace all values that said 
`"group.\(this.hostAppBundleIdentifier)" `
and I set them manual 
`"group.com.myappidname"`
 and that solved the problem and no longer gives more error [Error: file type is Invalid] iOS

**Comment by fukemy** [comment]
@luigbren I tried but not working to me
