### ISSUE TITLE
[Error: file type is Invalid]

### ISSUE THREAD

**Issue by sobhaeliza** [ajith-ab/react-native-receive-sharing-intent#17]
Xcode - Version 11.5 
react-native: 0.62.2

I could not upload any type of files, always getting the error : [Error: file type is Invalid].

**Comment by duylinhdang1998** [comment]
How do fix that, please 
thanks

**Comment by luigbren** [comment]
> How do fix that, please thanks


hello, I spent many hours trying to make it work on iOS and nothing, until I got it to work, I read that it was a problem with the group.name, simply I opened the file "ShareViewController.swift", search and replace all values that said 
`"group.\(this.hostAppBundleIdentifier)" `
and I set them manual 
`"group.com.myappidname"`
 and that solved the problem and no longer gives more error [Error: file type is Invalid] iOS
