### ISSUE TITLE
How to Hide popup in iOS devices

### ISSUE THREAD

**Issue by jaiprakashPal** [ajith-ab/react-native-receive-sharing-intent#18]
I'm using React Native version 0.62.2 and Xcode 11.2.1.
After select image for share, showing this popup
![IMG_1524](https://user-images.githubusercontent.com/67465872/85853102-9094b700-b7cf-11ea-8ef2-f2726f88cf76.PNG)

**Comment by dotemacs** [comment]
When you click on 'Cancel' does that not remove the share screen?

Is this what you meant?

**Comment by jaiprakashPal** [comment]
NO, When I select images for sharing, this popup should not come and open the app directly

**Comment by SafdarSikander** [comment]
same here, how can I disable this popup?

**Comment by tommynordli** [comment]
Same, haven't been able to bypass this either

**Comment by tommynordli** [comment]
If you move the logic in `ShareViewController.swift` to `viewDidLoad` instead of `didSelectPost`, you will be redirected directly to the app. 
<img width="693" alt="Screenshot 2020-07-02 at 13 13 34" src="https://user-images.githubusercontent.com/5970898/86352390-02ed1780-bc66-11ea-8469-400eac01d734.png">

**Comment by ThadeusAjayi** [comment]
> If you move the logic in `ShareViewController.swift` to `viewDidLoad` instead of `didSelectPost`, you will be redirected directly to the app.
> <img alt="Screenshot 2020-07-02 at 13 13 34" width="693" src="https://user-images.githubusercontent.com/5970898/86352390-02ed1780-bc66-11ea-8469-400eac01d734.png">

This doesn't work on iOS 13, that's what I have to test

**Comment by jaiprakashPal** [comment]
Thanks

**Comment by ThadeusAjayi** [comment]
@jaiprakashPal  What's the solutions please ?

**Comment by ntvinhit** [comment]
Still not works.

Facebook faces this issue too, so is this a bug of iOS?

**Comment by jaypeeji** [comment]
> @jaiprakashPal What's the solutions please ?

https://github.com/ajith-ab/react-native-receive-sharing-intent/issues/18#issuecomment-653507106

**Comment by jaypeeji** [comment]
> Still not works.
> 
> Facebook faces this issue too, so is this a bug of iOS?

https://github.com/ajith-ab/react-native-receive-sharing-intent/issues/18#issuecomment-653507106

**Comment by ntvinhit** [comment]
> > Still not works.
> > Facebook faces this issue too, so is this a bug of iOS?
> 
> [#18 (comment)](https://github.com/ajith-ab/react-native-receive-sharing-intent/issues/18#issuecomment-653507106)

I mean the solution stills not works.

**Comment by Asaf-Chio** [comment]
same issue
is there a solution for this one ?

**Comment by fukemy** [comment]
still no solution in 2023

**Comment by fukemy** [comment]
OK I found solution, just extend UIViewController

**Comment by EugeniuszX** [comment]
@fukemy could you please show the code?

**Comment by fukemy** [comment]
> @fukemy could you please show the code? 

**class ShareViewController : UIViewController**

**Comment by Melber17** [comment]
@fukemy yeah, I tried like that. But then there is many errors
