### ISSUE TITLE
Only contentUri, no filePath when shared from some apps

### ISSUE THREAD

**Issue by NanduKkd** [ajith-ab/react-native-receive-sharing-intent#19]
While sharing files from whatsapp or filemanager, the object received by the function passed into getReceivedFiles has only contentUri, all other values such as filePath, extension, mimeType are null. If this is not a bug, a feature like resolving the content uri into file path can be added, which would be greatly helpful.

**Comment by ajith-ab** [comment]
@NanduKkd When sharing from some of the apps like **what's app**  only we get content uri. whats app does not provide the file path. so this is not an issue

**Comment by NanduKkd** [comment]
Then is there any way to get the file path from the content Uri? Help me please!

**Comment by jaiprakashPal** [comment]
Any help?

**Comment by NanduKkd** [comment]
@jaiprakashPal I wanted to copy the file into another path using rn-fetch-blob. I used the fetch function of js to get a blob and then converted it to base64 and saved that into another file:
```
async function copy_uri(uri){
	const blob = await (await fetch(uri)).blob()
	await new Promise(resolve => {
		var reader = new FileReader();
		reader.readAsDataURL(blob); 
		reader.onloadend = () => {
			var base64data = reader.result;                
			let pth = FetchBlob.fs.dirs.SDCardDir+'/mydir/copied.jpg'
			RNFetchBlob.fs.writeFile(pth, reader.result.substr(base64data.indexOf(',')+1), 'base64').then(() => {
				blob.close()
				resolve();
			});
		}
	})
}
```
