### ISSUE TITLE
ReceiveSharingIntent.getReceivedFiles throws error

### ISSUE THREAD

**Issue by Choco-Dev** [ajith-ab/react-native-receive-sharing-intent#2]
Hi, thanks for this great package

i'm going to use this package to share URLs from browser to my rn application. And when my app opens after clicking on it in sharing menu, my app crashes with bellow error.
any thoughts ?

<img width="525" alt="Screen Shot 2020-06-05 at 1 46 32 PM" src="https://user-images.githubusercontent.com/53306166/83859323-fd69e380-a732-11ea-9ca3-a0f21cc7bf55.png">

**Comment by Choco-Dev** [comment]
Oh i just found that i had not run `npx pod-install` in my project.
actually it has not mentioned in documents as a installation step

**Comment by sawndur** [comment]
What version of react native are you using?
