### ISSUE TITLE
Stop your spamming activities!

### ISSUE THREAD

**Issue by ortonomy** [ajith-ab/react-native-receive-sharing-intent#27]

**Comment by ortonomy** [comment]
You can change the issue now if you want, I've captured it all in an article: https://dev.to/ortonomy/how-not-to-get-people-to-use-your-npm-library-16cm

**Comment by hackrx** [comment]
😂 seriously this guy is insane, I have also seen his comment almost every-where in this repository,
@ortonomy thanks for mentioning this guy on dev.to blog.

**Comment by YannickLeon** [comment]
After 2 days of trying to implement the react-native-share-extensions, I tried his module despite the spam and it worked after like 10 minutes of setup. So if anyone is having trouble you can try this package and maybe it works for you aswell.

**Comment by ortonomy** [comment]
@YannickLeon -- Or just follow this : https://github.com/alinz/react-native-share-extension/issues/209

**Comment by fukemy** [comment]
i confirmed react-native-receive-sharing-intent is bad, and react-native-share-extension is better, this spammer want spam for get donate, or something?
 1. Documents not fully explain
 2. No example detail
 3. Too many issues without help
 4. No update since long times
