### ISSUE TITLE
Android every share seems to come twice

### ISSUE THREAD

**Issue by jtkDvlp** [ajith-ab/react-native-receive-sharing-intent#32]
Every share seems to come twice

**Comment by jtkDvlp** [comment]
Fixes the issue for #29

**Comment by utsav1322** [comment]
Facing the same issue
Share data coming more the one time

[Mon Aug 17 2020 21:09:22.861]  LOG      files [{"contentUri": "content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F61/REQUIRE_ORIGINAL/NONE/659338401", "extension": "jpg", "fileName": "LandWater13.jpg", "filePath": "/storage/emulated/0/Download/LandWater13.jpg", "mimeType": "image/jpeg", "text": null, "weblink": null}, {"contentUri": "content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F73/REQUIRE_ORIGINAL/NONE/959162768", "extension": "jpg", "fileName": "Misc11.jpg", "filePath": "/storage/emulated/0/Download/Misc11.jpg", "mimeType": "image/jpeg", "text": null, "weblink": null}, {"contentUri": "content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F60/REQUIRE_ORIGINAL/NONE/1804740013", "extension": "jpg", "fileName": "LandWater12.jpg", "filePath": "/storage/emulated/0/Download/LandWater12.jpg", "mimeType": "image/jpeg", "text": null, "weblink": null}]
[Mon Aug 17 2020 21:09:37.105]  LOG      files [{"contentUri": "content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F61/REQUIRE_ORIGINAL/NONE/659338401", "extension": "jpg", "fileName": "LandWater13.jpg", "filePath": "/storage/emulated/0/Download/LandWater13.jpg", "mimeType": "image/jpeg", "text": null, "weblink": null}, {"contentUri": "content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F73/REQUIRE_ORIGINAL/NONE/959162768", "extension": "jpg", "fileName": "Misc11.jpg", "filePath": "/storage/emulated/0/Download/Misc11.jpg", "mimeType": "image/jpeg", "text": null, "weblink": null}, {"contentUri": "content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F60/REQUIRE_ORIGINAL/NONE/1804740013", "extension": "jpg", "fileName": "LandWater12.jpg", "filePath": "/storage/emulated/0/Download/LandWater12.jpg", "mimeType": "image/jpeg", "text": null, "weblink": null}]


"react": "16.11.0",
"react-native": "0.62.2",
"OS": "ANDROID",
"react-redux": "5.0.6",
"redux": "3.7.2",

Please fix this issue as soon as possible

**Comment by utsav1322** [comment]
@ajith-ab 
Please fix this issue as soon as possible
Because this is making duplicates of data and can not use the library for now because o this issue

**Comment by jtkDvlp** [comment]
See #29 for fix

**Comment by utsav1322** [comment]
@jtkDvlp 
I tried but didn't work for me
**is there anything I need to take care in specific**
I need a file path for every image I get

"contentUri":"content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F61/REQUIRE_ORIGINAL/NONE/659338401",
 "extension": "jpg", 
"fileName": "LandWater13.jpg", 
**"filePath": "/storage/emulated/0/Download/LandWater13.jpg",**
 "mimeType": "image/jpeg", 
"text": null, 
"weblink": null

**I need this much data of shared images**

**Comment by utsav1322** [comment]
@jtkDvlp **Why did you remove** android/src/main/java/com/ajithab/RNReceiveSharingIntent/ReceiveSharingIntentGetFileDirectory.java

**Comment by jtkDvlp** [comment]
> I tried but didn't work for me
is there anything I need to take care in specific
I need a file path for every image I get

You have to clear received files directly in your handler to prevent triggering twice. I removed the "filePath" property because its not working reliable and in my usecase there is no need for filePath. To read the file contents "contentUri" is the way. For reliable file information see https://developer.android.com/training/secure-file-sharing/retrieve-info

> Why did you remove ReceiveSharingIntentGetFileDirectory.java ?

As mentioned above, its not working for me. If you need it you can just use the last commit preventing the trigger issue. https://github.com/ajith-ab/react-native-receive-sharing-intent/pull/29/commits/8dd421fbc89c9387d7f5a0b073188956dd5b1412

**Comment by utsav1322** [comment]
@jtkDvlp thanks for replay
I will look into it

**Comment by robsco** [comment]
"You have to clear received files directly in your handler"

Do you perhaps have an example of this?  I'm seeing repeated calls for my function provided to getReceivedFiles(), and even if calling ReceiveSharingIntent.clearReceivedFiles(); inside there makes no difference.

I'm also seeing repeats completely at random, I can go 10 minutes testing without issue, then all of a sudden, without any code changes, I start getting 2+ repeats, which then obviously results in duplicate processing.

**Comment by boypanjaitan16** [comment]
Any update on this ?

**Comment by jtkDvlp** [comment]
@robsco Actually you just clear within your function, that handles the incoming share. Do you have the version with the fix #29 ? Maybe you have another issue with running conditions? Try to reproduce your issue with an minimal example and post it here.

**Comment by robsco** [comment]
I actually ripped this thing apart and implemented it myself, in Java/Android anyway, I'm still yet to do iOS, this library ended up having a load of bloat and I preferred understanding it all better anyway.

Let me know if you want a copy of what I did.

**Comment by jtkDvlp** [comment]
> I actually ripped this thing apart and implemented it myself, in Java/Android anyway...I preferred understanding it all better anyway.
👍 

> this library ended up having a load of bloat
agree 100%

> Let me know if you want a copy of what I did.
Maybe you want to share it via github and paste your repo, that would be nice 👍

**Comment by robsco** [comment]
I wrote it all up in a doc for my future self.

https://docs.google.com/document/d/1Eq_ReoTkJ7EOlS9eZCAPdu5-dT9u2jQLssA1jmi6BMs/edit?usp=sharing
