### ISSUE TITLE
Get error when i build Xcode ios

### ISSUE THREAD

**Issue by duylinhdang1998** [ajith-ab/react-native-receive-sharing-intent#38]
I got the error when I run-ios
![image](https://user-images.githubusercontent.com/40199004/95283636-7b2b3080-0886-11eb-9eef-a6fb0616229c.png)
I run your example get the same error

**Comment by janfi** [comment]
Hi, I have the same error. Do you have a solution ? Thanks.

**Comment by duylinhdang1998** [comment]
You can following link https://stackoverflow.com/questions/57903395/about-100-error-in-xcode-undefined-symbols-for-architecture-x86-64-upgraded-re

**Comment by janfi** [comment]
Thanks.

**Comment by krupalikevadiya** [comment]
I just added libswiftWebKit.tbd to

Link Binary with Libraries (from project, Build Phases)

and the build was successful.
