### ISSUE TITLE
Make CFBundleURLSchemes customizable

### ISSUE THREAD

**Issue by thomaschaaf** [ajith-ab/react-native-receive-sharing-intent#45]
Currently the CFBundleURLSchemes is hardcoded and always needs to be 'ShareMedia'. This should be configurable.

**Comment by nschild** [comment]
@thomaschaaf 
In our configuration, we have:
```
<key>CFBundleURLSchemes</key>
<array>
	<string>ShareMedia</string>
	<string>{some value}</string>
	<string>{another value}</string>
</array>
```

Would this format work for you?
