### ISSUE TITLE
Avoid multiple instance of the app

### ISSUE THREAD

**Issue by fabio-C** [ajith-ab/react-native-receive-sharing-intent#5]
I tried this library in Android and it works, but what I need is to have always only one instance of the app. 

Using this library with **_android:launchMode="singleTop"_**, everytime I share somethings a new instance of the app is created, so at the end I have the same app opened multiple times in background.

If I set: **_android:documentLaunchMode="never"_**, I got only one instance opened, but I got [this issue](https://github.com/ajith-ab/react-native-file-share-intent/issues/27).

Is there a solution for that?

**Comment by bacarybruno** [comment]
I'm also looking for a solution. I have tried several things but I have not been able to find a solution.

**Comment by danielmark0116** [comment]
Same here :) I was messing around with different `launchMode` and `documentLaunchMode` - it was either opening a new instance or wasn't working

**Comment by n-popov-geniusee** [comment]
have same issue too

**Comment by bacarybruno** [comment]
I managed to make it work. Here is what I did :
- On AndroidManifest.xml (`android/app/src/main/AndroidManifest.xml`)
set `android:launchMode="singleTask"`
- On MainActivity on your react-native app (`android/app/src/main/java/com/YOUR_APP/MainActivity.java`) :
``` Java
// on top of your file
import android.content.Intent;

// on your MainActivity Class body
@Override
public void onNewIntent(Intent intent) {
  super.onNewIntent(intent);
  setIntent(intent);
}
```
- In your js file :
```JS
// on top of your file
import { AppState } from 'react-native';

// inside your component
useEffect(() => {
  // handleSharingIntent is the function that calls ReceiveSharingIntent.getReceivedFiles()
  handleSharingIntent(); // will be called on app launch
  AppState.addEventListener('change', (status) => {
    if (status === 'active') {
      handleSharingIntent(); // will be called when the app goes foreground
    }
  })
}, [handleSharingIntent])
```

Hope it will help you.

**Comment by ajith-ab** [comment]
@bacarybruno Thanks For u Update I was updated in GitHub repository and latest version of npm package

thanks
Ajith A B

**Comment by hengkx** [comment]
same problem

**Comment by hengkx** [comment]
```ts
React.useEffect(() => {
    ReceiveSharingIntent.getReceivedFiles(
      (fileList: any[]) => {
       console.log(fileList);// content repeat
      },
      (error: any) => {
        console.log(error);
      },
    );

    return () => {
      ReceiveSharingIntent.clearReceivedFiles();
    };
  }, []);
```

**Comment by jjhampton** [comment]
Thanks @bacarybruno , that fix in https://github.com/ajith-ab/react-native-receive-sharing-intent/issues/5#issuecomment-643661367 worked for me .

**Comment by ntvinhit** [comment]
The issue is still. 
singleTask works on most Android devices but not Samsung.

**Comment by robbiedood** [comment]
@bacarybruno Thanks for your solution! Do you define the function "handleSharingIntent" inside useEffect or outside useEffect ? Hope to hear your expertise.

> I managed to make it work. Here is what I did :
> 
> * On AndroidManifest.xml (`android/app/src/main/AndroidManifest.xml`)
>   set `android:launchMode="singleTask"`
> * On MainActivity on your react-native app (`android/app/src/main/java/com/YOUR_APP/MainActivity.java`) :
> 
> ```java
> // on top of your file
> import android.content.Intent;
> 
> // on your MainActivity Class body
> @Override
> public void onNewIntent(Intent intent) {
>   super.onNewIntent(intent);
>   setIntent(intent);
> }
> ```
> 
> * In your js file :
> 
> ```js
> // on top of your file
> import { AppState } from 'react-native';
> 
> // inside your component
> useEffect(() => {
>   // handleSharingIntent is the function that calls ReceiveSharingIntent.getReceivedFiles()
>   handleSharingIntent(); // will be called on app launch
>   AppState.addEventListener('change', (status) => {
>     if (status === 'active') {
>       handleSharingIntent(); // will be called when the app goes foreground
>     }
>   })
> }, [handleSharingIntent])
> ```
> 
> Hope it will help you.
