### ISSUE TITLE
Not Working on IOS 14.3 - Shared Files do not open React Native App (App to App Sharing)

### ISSUE THREAD

**Issue by charlesoruko** [ajith-ab/react-native-receive-sharing-intent#55]
Shared Files from IOS file manager and other IOS apps do not redirect or open the main App after i press the post button.
The app however accepts and opens apps via Airdrop , but not APP to APP sharing.

anyone with a working example please help.
IOS 14.3
XCODE 12.3
"react-native-receive-sharing-intent": "^1.1.0",
"react": "16.13.1",
"react-native": "0.63.3",

**Comment by wmdev-alex** [comment]
Same for me

**Comment by isot1990** [comment]
did you find the solution @charlesoruko ?

**Comment by charlesoruko** [comment]
> did you find the solution @charlesoruko ?

The Plugin works on 
IOS 14.4 , XCODE 12.4 ,
"react-native-receive-sharing-intent": "^1.1.0",
"react-native": "0.63.3",     "react": "16.13.1",
Works without the shareextension file try removing it and see if it works.

**Comment by lucijafrkovic** [comment]
@charlesoruko what file is that?

**Comment by charlesoruko** [comment]
> @charlesoruko what file is that?

the Share Extension file that you need to create as per the installation instructions

**Comment by ajith-ab** [comment]
You need to change target version of share extension.
