### ISSUE TITLE
Can't ./gradlew bundleRelease because of this plugin. The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead. 

### ISSUE THREAD

**Issue by pdooo** [ajith-ab/react-native-receive-sharing-intent#59]
> Configure project :react-native-receive-sharing-intent
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead.

**Comment by pdooo** [comment]
@ajith-ab

**Comment by ajith-ab** [comment]
It would be fixed on new Version
