### ISSUE TITLE
Failed to install from yarn

### ISSUE THREAD

**Issue by kokitang** [ajith-ab/react-native-receive-sharing-intent#6]
Refer to the image, it seems need to specify the `SWIFT_VERSION` in the .podspec file.

![image](https://user-images.githubusercontent.com/17448093/84490574-ee0c0c80-acd5-11ea-8bbd-755a117b127b.png)

**Comment by ajith-ab** [comment]
@kokitang Which version of React Native you are using ??

Thanks & Regards
Ajith A B

**Comment by shawnzheng99** [comment]
Same here.

```
React Native 0.60.5
pod 1.7.5
```

Thanks

**Comment by vishnuindrabalan** [comment]
> I'm using npm got the same error here at `pod install`
> 
> ```
> React Native 0.60.5
> pod 1.7.5
> ```
> 
> Thanks

Any updates on this? 
I'm using React native 0.61.5

**Comment by sreedhu-7** [comment]
I'm also facing this issue.

**Comment by jjring** [comment]
I was able to fix this by adding an empty swift file to my main project and my test project. I didn't need to specify SWIFT_VERSION in the pod file.
