### ISSUE TITLE
Error: ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'

### ISSUE THREAD

**Issue by javierdac** [ajith-ab/react-native-receive-sharing-intent#61]
if i follow the instructions to run i get: 

ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'
ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'

Undefined symbol: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreMIDI

Even if i run the example project i get the same error

This is happening in IOS

**Comment by javierdac** [comment]
this is happening in IOS

**Comment by GobindaSaha** [comment]
I'm getting the same error over and over again. I have no idea why these errors showing up in Xcode 12.4. It works fine with Xcode 11.4 but whenever I try to implement the same pugin for Xcode 12.4 it throws the same below error all the time.

If you get any solution over this please let me know @javierdac  Thank you.
![Screen Shot 2021-03-18 at 5 16 06 PM](https://user-images.githubusercontent.com/34857385/111621590-2cf36380-880e-11eb-8843-9ca1d9ec474b.png)

**Comment by lsmacedo** [comment]
Managed to fix this issue by following the steps shared by fritzfr: "Fixed it by placing a File.swift in our root and then let Xcode create a Objective-C bridging header.". Worked for me in Xcode 12.4.
https://github.com/AgoraIO-Community/react-native-agora/issues/266

**Comment by ajith-ab** [comment]
@lsmacedo Great Thank you.
