### ISSUE TITLE
ReferenceError: mimes is not defined

### ISSUE THREAD

**Issue by alexandrumogic** [ajith-ab/react-native-receive-sharing-intent#67]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-receive-sharing-intent@1.1.0` for the project I'm working on.

TypeScript is returning this error: ReferenceError: mimes is not defined
This is because export default does not need a named export.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-receive-sharing-intent/mimeType.js b/node_modules/react-native-receive-sharing-intent/mimeType.js
index 58958f4..6779df0 100644
--- a/node_modules/react-native-receive-sharing-intent/mimeType.js
+++ b/node_modules/react-native-receive-sharing-intent/mimeType.js
@@ -1,4 +1,4 @@
-export default  mimes = {  
+export default {  
     ".323": "text/h323",
     ".3g2": "video/3gpp2",
     ".3gp": "video/3gpp",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ajith-ab** [comment]
New Version it would be fixed now.

Thanks,
Ajith A B
