### ISSUE TITLE
Undefined symbol: Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)

### ISSUE THREAD

**Issue by azesmway** [ajith-ab/react-native-receive-sharing-intent#68]
Xcode Version 12.5 (12E262)

the error happens at this point:
`let selectorOpenURL = sel_registerName("openURL:")`

can anyone know the solution?

**Comment by angeria** [comment]
How did you solve this?

**Comment by azesmway** [comment]
I tried to build the release and it was assembled, there was a problem in the debug mode, I set all the settings for the sharing as in the release and in the debug it also worked

**Comment by azesmway** [comment]
> @azesmway I'm also having this issue. Please can you be a bit more explicit on how you got this resolved?

Hi
When I created a new share extension, the build settings for it had different debug and release settings. I have set all the settings as for the release. The error is gone and is going to be fine and working

**Comment by matamicen** [comment]
I have the same error with another SHARE library, it works on RELEASE but don't compile in debug ... I tried @azesmway approach to keep the debug parameters the same as release but without success. 
Any help will be appreciated.

Thanks.

**Comment by iamitkhatkar** [comment]
if someone still facing the issue then you can remove the
 `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)`
 from the share target -> build settings -> library search path. 

referenced from https://stackoverflow.com/a/67405812/6815914

**Comment by prasanthvenkatachalam** [comment]
Saved my day, Thanks

**Comment by Jonovono** [comment]
@iamitkhatkar a god
