### ISSUE TITLE
Error: java.lang.NullPointerException in version 2.0.0

### ISSUE THREAD

**Issue by prasanthvenkatachalam** [ajith-ab/react-native-receive-sharing-intent#84]
When opening app, I am facing android.content.intent.hasextra(java.lang.String) on null object reference
![Error](https://user-images.githubusercontent.com/36700160/126777808-4531be54-caf7-4aa4-9f5f-370b480148cd.jpg)

**Comment by prasanthvenkatachalam** [comment]
solved by following below steps.
Open node_modules>react-native-receive-sharing-intent>java>com.reactnativereceivesharingintent>ReceiveSharingIntentModule.java> and comment this line mActivity.setIntent(null).
its works for me

**Comment by gk704297** [comment]
@prasanthvenkatachalam  Thanks, your solution worked for me too. Hope it will help some other folks.
