### ISSUE TITLE
[Error: file type is Invalid] iOS

### ISSUE THREAD

**Issue by vjann** [ajith-ab/react-native-receive-sharing-intent#9]
My app shows up correctly in the share menu and it opens the app fine, but I'm getting an log
`{"url": "ShareMedia://dataUrl=ShareKey#text"}` (same with #media)
and error
`Error: file type is Invalid`
for both simulator iphone 11 pro and a real iphone 8. It works great on Android.

I don't think I missed any steps in the installation-- Did the "ShareKey" in ios/{share extension/ShareViewController.swift needed to be replaced by anything?

I'm using "react-native": "^0.62.2", "react-native-receive-sharing-intent": "^1.0.4",
xcode 11.5. Thank you.

**Comment by ajith-ab** [comment]
@vjann Please give a file type of media you are sharing

Thanks 
Ajith A B

**Comment by vjann** [comment]
For all types. I've tried sharing an url from Safari like the demo, plain text, and images from iphotos.

**Comment by ajith-ab** [comment]
Ok then, please try our example code in Github repo. I think to miss Configuration of Share Extension

Thanks
Ajith A B

**Comment by ajith-ab** [comment]
@vjann I ve tested with your react-native version. I have worked properly. please recheck your configurations. so I've closed this issue

Thank
Ajith A B
Happy Coding :)

**Comment by vjann** [comment]
You were right, my bundle id was wrong in the app groups. Thank you!

**Comment by duylinhdang1998** [comment]
what did you miss? Please give me details

**Comment by charlesoruko** [comment]
Am still having this problem , 
could we get an updated example that works , they are all about 8 months old ,
or some help to fix this issue on IOS

**Comment by luigbren** [comment]
> Am still having this problem , could we get an updated example that works , they are all about 8 months old , or some help to fix this issue on IOS

hello, I spent many hours trying to make it work on iOS and nothing, until I got it to work, I read that it was a problem with the group.name, simply I opened the file "ShareViewController.swift", search and replace all values that said 
`"group.\(this.hostAppBundleIdentifier)" `
and I set them manual 
`"group.com.myappidname"`
 and that solved the problem and no longer gives more error [Error: file type is Invalid] iOS
