### ISSUE TITLE
Sharing doesn't work on ios - react native 0.64.2

### ISSUE THREAD

**Issue by aliberski** [ajith-ab/react-native-receive-sharing-intent#93]
After upgrading to the latest react native the share functionality stopped working on iOS.
The error message from `getReceivedFiles` method says:
> "file type is Invalid"

I tried with many file types (.heic, .jpg, etc.), but the error is the same.

**Comment by IbrahimCanKALYA** [comment]
same issue

**Comment by luigbren** [comment]
hello, I spent many hours trying to make it work on iOS and nothing, until I got it to work, I read that it was a problem with the group.name, simply I opened the file "ShareViewController.swift", search and replace all values that said 
`"group.\(this.hostAppBundleIdentifier)" `
and I set them manual 
`"group.com.myappidname"`
 and that solved the problem and no longer gives more error [Error: file type is Invalid] iOS

**Comment by professorkolik** [comment]
For us with @aliberski the issue was missing App Group in our Target project, after specifying it all is working again
